// Agent-Lab ESM Project – generated by ChatGPT
// Version ID: 20250828-1105

export interface Tool {
  name: string;
  description: string;
  run: (input: any) => Promise<any>;
}

export interface AgentConfig {
  name: string;
  description: string;
  version: string;
  systemPrompt: string;
  tools?: Tool[];
  inputSchema?: object;
  outputSchema?: object;
}

export class BaseAgent {
  name: string;
  description: string;
  version: string;
  systemPrompt: string;
  tools: Tool[];

  constructor(config: AgentConfig) {
    this.name = config.name;
    this.description = config.description;
    this.version = config.version;
    this.systemPrompt = config.systemPrompt;
    this.tools = config.tools || [];
  }

  async run(input: any): Promise<any> {
    const outputs: Record<string, any> = {};
    for (const tool of this.tools) {
      try {
        outputs[tool.name] = await tool.run(input);
      } catch (err) {
        outputs[tool.name] = { error: (err as Error).message };
      }
    }
    return {
      agent: this.name,
      version: this.version,
      outputs,
    };
  }
}
