// server/agents/__TEMPLATE__.agent.ts (v1.0)

// Agent-Lab ESM Project – generated by ChatGPT
// Version ID: 20250828-0835

import { BaseAgent, AgentConfig, Tool } from "../framework/agent.ts";

// Example tool stub (replace with imports from server/tools/)
const echoTool: Tool = {
  name: "echo",
  description: "Returns the input unchanged",
  run: async (input: any) => input,
};

export class TemplateAgent extends BaseAgent {
  constructor(config?: Partial<AgentConfig>) {
    super({
      name: config?.name || "TemplateAgent",
      description: config?.description || "Example agent built from template",
      version: config?.version || "0.1",
      systemPrompt: config?.systemPrompt || "You are a helpful template agent.",
      tools: config?.tools || [echoTool],
    });
  }

  // Optional: override run() if you want custom execution flow
  async run(input: any): Promise<any> {
    // Example: prepend a message before calling base run()
    const baseResults = await super.run(input);
    return {
      ...baseResults,
      note: "This response was generated by the TemplateAgent.",
    };
  }
}
