// agents/cli-test-bot.agent.ts
// Auto-generated by Agent-Lab CLI

import { BaseAgent } from "../server/agent-builder/agent.ts";

export class CLITestBotAgent extends BaseAgent {
  constructor() {
    super({
      name: "CLI Test Bot",
      description: "A test from CLI",
      version: "0.1",
      systemPrompt: `You are CLI Test Bot. A test from CLI`,
      tools: [
  "yahoo-finance"
],
      inputSchema: {
  "query": {
    "type": "string",
    "required": true,
    "description": "User query"
  }
},
      outputSchema: {
  "result": {
    "type": "string",
    "required": true,
    "description": "Agent response"
  }
}
    });
  }

  protected async execute(input: Record<string, any>): Promise<any> {
    this.log("Starting execution with input:", input);
    
    // Your custom agent logic goes here
    // Input fields: query
    
    // Process based on selected tools: yahoo-finance
    
    // Return structured output
    const result = {
      result: "TODO: Implement result logic",
      timestamp: new Date().toISOString(),
      agent: this.config.name
    };
    
    this.log("Execution completed:", result);
    return result;
  }
}

// Default export for Agent-Lab runner compatibility
export default async function run(args: string[]) {
  const agent = new CLITestBotAgent();
  return await agent.run(args);
}
