// server/agents/registry.ts (v1.0)

// Agent-Lab ESM Project – generated by ChatGPT
// Version ID: 20250828-0835

import { TemplateAgent } from "./__TEMPLATE__.agent.ts";

export const agents = {
  template: new TemplateAgent(),
  // stock: new StockAgent(),   // Example: after you port stock.agent.ts
  // research: new ResearchAgent(),
};
